AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - spec/spec_helper.rb
    - Gemfile
    - Gemfile.lock
    - vendor/**/*
Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
Metrics/LineLength:
  Max: 100
